# Generated by Django 5.0.6 on 2024-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2nd A', '2nd A'), ('2nd C', '2nd C'), ('1re A', '1re A'), ('1re D', '1re D'), ('Tle A', 'Tle A'), ('Tle D', 'Tle D')], default='6e', max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
