# Generated by Django 5.0.6 on 2024-06-05 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_evaluation_lesson_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mpeg', 'avi'])]),
        ),
    ]
