# Generated by Django 5.0.6 on 2024-06-17 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lesson_image_alter_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.matiere'),
        ),
    ]
