# Generated by Django 5.0.6 on 2024-06-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_lesson_evaluation_remove_niveau_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='niveaux',
            field=models.ManyToManyField(related_name='niveaux', to='app.niveau'),
        ),
    ]
