# Generated by Django 5.0.6 on 2024-06-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_matiere_niveaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='niveaux',
        ),
    ]
