# Generated by Django 5.0.6 on 2024-07-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_matiere_niveaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='app.niveau'),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='niveau',
            field=models.CharField(choices=[('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2nd A', '2nd A'), ('2nd C', '2nd C'), ('1re A', '1re A'), ('1re D', '1re D'), ('Tle A', 'Tle A'), ('Tle D', 'Tle D')], default='6e', max_length=10, unique=True),
        ),
    ]
