# Generated by Django 5.0.6 on 2024-07-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_quiz_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse_quiz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='titre',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Reponse_Quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
