# Generated by Django 5.0.6 on 2024-07-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_quiz_question_reponse_quiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reponse_Quiz',
            new_name='ReponseQuiz',
        ),
    ]
