# Generated by Django 5.0.6 on 2024-07-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_reponse_quiz_reponsequiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
