# Generated by Django 5.0.6 on 2024-07-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='note',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='moyenne',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='niveau',
            name='moyenne',
            field=models.FloatField(default=0.0),
        ),
    ]
