# Generated by Django 5.0.6 on 2024-07-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_lesson_note_matiere_moyenne_niveau_moyenne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='note',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='moyenne',
        ),
        migrations.RemoveField(
            model_name='niveau',
            name='moyenne',
        ),
    ]
