# Generated by Django 5.0.6 on 2024-06-04 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Adresse e-mail invalide')])),
                ('type', models.CharField(choices=[('enseignant', 'eleve'), ('eleve', 'eleve')], default='eleve', max_length=20)),
            ],
        ),
    ]
