# Generated by Django 5.0.6 on 2024-07-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0003_rename_userprofile_utilisateur'),
        ('app', '0012_lesson_description_alter_lesson_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.niveau'),
        ),
    ]
