# Generated by Django 5.0.6 on 2024-07-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0004_utilisateur_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='moyenne',
            field=models.FloatField(default=0.0),
        ),
    ]
