# Generated by Django 5.0.6 on 2024-07-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0005_utilisateur_moyenne'),
        ('app', '0023_remove_lesson_note_remove_matiere_moyenne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='quiz_complets',
            field=models.ManyToManyField(blank=True, related_name='quiz_complets', to='app.quiz'),
        ),
    ]
