# Generated by Django 5.0.6 on 2024-07-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0006_utilisateur_quiz_complets'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='notes',
            field=models.IntegerField(default=0),
        ),
    ]
