# Generated by Django 5.0.6 on 2024-07-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0007_utilisateur_notes'),
        ('app', '0023_remove_lesson_note_remove_matiere_moyenne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='quiz_complets',
            field=models.ManyToManyField(blank=True, null=True, related_name='quiz_complets', to='app.quiz'),
        ),
    ]
